### ISSUE TITLE
Erros com arquivos compartilhados e edição

### ISSUE THREAD

**Issue by rafaelkillua** [cesar-neto/primeira-entrega-si#1]
Seguinte, compartilhei 2 arquivos com outra conta (rafael2), um para edição e um para leitura.
Na conta rafael2 tem as opções de deletar o arquivo. Quando deletei os 2, ficaram na lista de compartilhados da conta rafael2 mas foram apagados da conta principal (estão na lixeira).

Sobre a edição, não está sendo permitido editar apenas o texto de um arquivo, só quando edita o nome também.

**Comment by cesar-neto** [comment]
Boa tarde, esse bug do botao excluir já foi identificado previamente pelo
grupo e ficou decidido ajeitar amanhã na reunião que foi marcada no slack
Quando a edição que falou, foi decisão do grupo fazer assim, quando editar
edita de uma vez seja oq for. É algo que precisa mudar?

**Comment by AlbertoWagner** [comment]
No meu computador ta pegando de boa foi um erro de um commit de um
integrante de um grupo que foi ajeita o não permiti aquivos com mesmo nome
por isso esse erro .

Em 17 de setembro de 2016 14:24, César Ferreira notifications@github.com
escreveu:

**Comment by AlbertoWagner** [comment]
Essa parte do compartilha agente vai tira a lixeira no primeiro caso depois
agente vai pensa em algo melhor .

Em 17 de setembro de 2016 14:32, Alberto Wagner de Oliveira <
alberto.oliveira@ccc.ufcg.edu.br> escreveu:

**Comment by rafaelkillua** [comment]
É que tipo, a pessoa pode querer editar só o texto sem mudar o nome ahueahue

**Comment by AlbertoWagner** [comment]
Correto, era para funciona de forma correta mais mexerão e deu erro , mais
no meu PC ta funcionado. sendo que nao vou commita porque minha versão ta
antiga aqui .

Em 17 de setembro de 2016 15:25, Rafael Sampaio Tavares <
notifications@github.com> escreveu:

**Comment by cesar-neto** [comment]
Massa, tinha sido decisão do grupo fazer dessa forma, amanhã iremos ajeitar
isso quando se juntarmos

**Comment by rafaelkillua** [comment]
Tranquilo, nem precisa ajeitar então kkk
